org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# termux で自前ビルドした aapt2 では、release の最適化段階が
# AndroidManifest.xml と resources.arsc を落とした APK を作る。
# debug では走らないが、release でも無効にしておく。
android.enableResourceOptimizations=false
